! SPDX-License-Identifier: Apache-2.0
! FRR baseline for leaf1, applied post-boot via `vtysh -f` (docker-sonic-vs ships no bgpcfgd,
! so CONFIG_DB BGP tables are never translated — this file is the BGP source of truth).
router bgp 65001
 bgp router-id 10.0.0.1
 no bgp ebgp-requires-policy
 bgp fast-external-failover
 neighbor 10.0.12.1 remote-as 65002
 neighbor 10.0.12.1 description leaf2-Ethernet0
 neighbor 10.0.12.1 timers 3 10
 neighbor 10.0.12.3 remote-as 65002
 neighbor 10.0.12.3 description leaf2-Ethernet4
 neighbor 10.0.12.3 timers 3 10
 address-family ipv4 unicast
  network 10.0.1.0/24
  maximum-paths 2
 exit-address-family
