! SPDX-License-Identifier: Apache-2.0
! FRR baseline for leaf2, applied post-boot via `vtysh -f` (docker-sonic-vs ships no bgpcfgd,
! so CONFIG_DB BGP tables are never translated — this file is the BGP source of truth).
router bgp 65002
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 bgp fast-external-failover
 neighbor 10.0.12.0 remote-as 65001
 neighbor 10.0.12.0 description leaf1-Ethernet0
 neighbor 10.0.12.0 timers 3 10
 neighbor 10.0.12.2 remote-as 65001
 neighbor 10.0.12.2 description leaf1-Ethernet4
 neighbor 10.0.12.2 timers 3 10
 address-family ipv4 unicast
  network 10.0.2.0/24
  maximum-paths 2
 exit-address-family
