# SPDX-License-Identifier: Apache-2.0
"""Pre-generated demo answers (§8.1 component 12): presentation insurance, not a runtime cache.

When ``demo_mode`` is on, the orchestrator serves these rehearsed explanations instead of calling
the model. Answers are keyed by (lesson, step, card_version); a card_version bump invalidates them.
The file is generated by ``scripts/gen_demo_answers.py`` and is optional — absence just falls back
to the live model.
"""

from __future__ import annotations

import os
from pathlib import Path

import yaml


def demo_path(explicit: Path | str | None = None) -> Path:
    if explicit is not None:
        return Path(explicit)
    env = os.environ.get("CHAOSLAB_DEMO_SCRIPT")
    if env:
        return Path(env)
    return Path.cwd() / "demo_script.yaml"


class DemoStore:
    """Lookup of rehearsed answers, gated on a matching card_version."""

    def __init__(self, data: dict | None = None) -> None:
        self.lessons: dict = (data or {}).get("lessons", {})

    def _entry(self, lesson_id: str, card_version: int) -> dict | None:
        entry = self.lessons.get(lesson_id)
        if entry and entry.get("card_version") == card_version:
            return entry
        return None

    def observe(self, lesson_id: str, step_id: str, card_version: int) -> str | None:
        entry = self._entry(lesson_id, card_version)
        return (entry or {}).get("observe", {}).get(step_id) if entry else None

    def impact(self, lesson_id: str, chaos_id: str, card_version: int) -> str | None:
        entry = self._entry(lesson_id, card_version)
        return (entry or {}).get("impact", {}).get(chaos_id) if entry else None


def load_demo_store(path: Path | str | None = None) -> DemoStore:
    target = demo_path(path)
    if not target.exists():
        return DemoStore()
    return DemoStore(yaml.safe_load(target.read_text()) or {})
