#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate demo_script.yaml: rehearsed explanations keyed by (lesson, step, card_version).

Runs the orchestrator (demo mode off) over each lesson's observe steps and enabled chaos options,
capturing the grounded explanations from the configured provider. With a real provider + API key
this yields production-quality answers; with the default fake provider it yields deterministic
placeholders. Presentation insurance for the rehearsed demo path — not a runtime cache.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from chaoslab.core.engine import build_orchestrator, catalogue  # noqa: E402
from chaoslab.settings import load_env, load_settings  # noqa: E402


def main() -> int:
    load_env()
    settings = load_settings().model_copy(update={"demo_mode": False})
    print(f"generating demo answers with provider={settings.provider}")

    output: dict = {"version": 1, "lessons": {}}
    for loaded in catalogue():
        lesson_id = loaded.id
        steps = loaded.lesson.steps
        entry: dict = {"card_version": loaded.lesson.meta.card_version, "observe": {}, "impact": {}}

        orch = build_orchestrator(lesson_id, settings)
        for index, step in enumerate(steps):
            if step.kind == "observe":
                orch.step_index = index
                entry["observe"][step.id] = orch.observe().explanation

        chaos_index = next(i for i, step in enumerate(steps) if step.kind == "chaos_select")
        for option in loaded.lesson.chaos_options:
            if not option.enabled:
                continue
            chaos_orch = build_orchestrator(lesson_id, settings)
            chaos_orch.step_index = chaos_index
            entry["impact"][option.id] = chaos_orch.select_chaos(option.id).explanation
            chaos_orch.restore()

        output["lessons"][lesson_id] = entry
        print(f"  {lesson_id}: {len(entry['observe'])} observe, {len(entry['impact'])} impact")

    target = REPO_ROOT / "demo_script.yaml"
    target.write_text(
        "# Generated by scripts/gen_demo_answers.py — regenerate with `make demo-answers`.\n"
        + yaml.safe_dump(output, sort_keys=False, allow_unicode=True, width=4096)
    )
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
